### PR TITLE
cleaned repo and added https support

### PR DESCRIPTION
**Pull request by lazakoa**
Supports https links now. The application cannot be used to share text snippets anymore.

### CODE REVIEW

**Review by francium — APPROVED** [review]

**Review by francium — APPROVED** [review]

**Review by francium — COMMENTED** [review]
Regarding 074da9b.

Check out git rebase.

You can merge small changes like this with previous commits so as to not create small, fragmented changes.

**Comment by ztasre** [comment]
Using blitzdb as a database. Replaced occurrences of "microURL" with "micro-url" in everything that isn't user facing.

**Comment by lazakoa** [comment]
Has a database now. Can potentially be extended to use mongo.

**Comment by lazakoa** [comment]
Merged small changes using git rebase.

**Comment by francium** [comment]
I don't want to use mongo, because there is absolutely no need for NoSQL. SQL will serve just fine. Leaving it in for now, will deal with it in the future. Right now it's good enough to get away from the file based systems that was there before.

**Comment by francium** [comment]
Some feedback, might be subjective, but I think it's worth considering.

- Module and source files should use `_` rather than `-` to make it importable (try importing a module with `-`, you'll see what I mean)
- Stylistic stuff
    - Comments should be sentences with proper grammar (capitaization, etc.)
    - Imports should be alphabetical (I seperate modules by builtin and 3rd party (os, sys and flask, validators for example)

**Pull request merged**
